name: pollapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  flutter_bloc: ^9.1.1
  http: ^1.1.0
  equatable: ^2.0.7
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.1
  get: ^4.6.6
  logger: ^2.0.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"